### ISSUE TITLE
Python: Error when writing h5 files 

### ISSUE THREAD

**Issue by mainarke** [oscarlab/graphene#1880] opened 2020-10-10 13:11 UTC
## Description of the problem
I tried to run Tensorflow with Graphene (without SGX for now). The training process was fine; but when I tried to save the trained model using save_model(), there was an error. Note that the same script runs fine without Graphene.

I also tried to use load_model() with Graphene to load existing model (trained&saved without Graphene); similar error occurred.

I used the exact same manifest/Makefile from the Pytorch example. (Examples/pytorch)

I am wondering if there is anything specific needs to be done when reading/writing the disk. Any help is appreciated!

## Expected results
After the training is done, the model should be saved onto the disk.

## Actual results
```
Traceback (most recent call last):
  File "./ae_train.py", line 142, in <module>
    ae = trainAE(x_train_all, x_test_all)
  File "/ae_base.py", line 461, in trainAE
    save_model(ae, pkname)
  File "/usr/lib/python3/dist-packages/tensorflow_core/python/keras/saving/save.py", line 109, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/usr/lib/python3/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 86, in save_model_to_hdf5
    f = h5py.File(filepath, mode='w')
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 105, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2847)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2805)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/build/h5py-qzs83i/h5py-2.7.1/h5py/h5f.c:2296)
OSError: Unable to create file (unable to flock file, errno = 38, error message = 'Function not implemented')
```

**Comment by mainarke** [comment] 2020-10-11 06:17
This error might be related to flock() syscall, according to [#1802](https://github.com/oscarlab/graphene/issues/1802). Is there a way to circumvent this?

**Comment by dimakuv** [comment] 2020-10-12 09:29
Yes, the root cause here is that Graphene currently doesn't emulate the `flock()` system call. This is on our list of TODOs.

I am not aware of a way to circumvent this error in TensorFlow. Maybe others have more experience with TF.

**Comment by lejunzhu** [comment] 2020-10-12 23:49
I did this when I was using TF 1.14:

```
def save_model(model):
    bio = io.BytesIO()
    with h5py.File(bio) as hf:
        k.models.save_model(model, hf)
    return bio.getvalue() 
```

Then you can write the return value using normal file IO. Similar to load_model().

**Comment by mainarke** [comment] 2020-10-13 03:21
Thanks to @lejunzhu, I have implemented the following two wrappers. The usage is the same as the original `load_model`, `save_model`:

```
from tensorflow.keras.models import load_model, save_model
import io, h5py, pickle

def save_model_wrapper(model, path):
    bio = io.BytesIO()
    save_model(model, h5py.File(bio,'w'))
    string = bio.getvalue()
    pickle.dump(string,open(path,'wb'))

def load_model_wrapper(path):
    string = pickle.load(open(path,'rb'))
    bio = io.BytesIO(string)
    return load_model(h5py.File(bio))
```

### Test Environment
Ubuntu 18.04
python version: `3.6.9`
tensorflow version: `1.15.3`
h5py version: `2.10.0`

The code can be run with Graphene LibOS, but I have not tested it with SGX=1.

### Note
If you encounter this error: `TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO`,
try to update the h5py package: `python -m pip install --upgrade h5py`

**Comment by dimakuv** [comment] 2021-07-22 10:19
@mainarke We recently implemented support for POSIX locks (but not `flock` actually). Assuming that your workload can fall-back to POSIX locks when it doesn't find flocks, your workload should work under latest Graphene.

So if this is still relevant, please try it on the latest Graphene version. Othewise I will consider this issue resolved and close it after a couple days.

**Comment by mkow** [comment] 2021-08-31 15:23
Closing because of no response from the reporter for quite some time (and the issue is likely to be resolved by now).

**Closed by mkow** 2021-08-31 15:23 UTC
