### ISSUE TITLE
ECDSA Attestation not working 

### ISSUE THREAD

**Issue by kamathhrishi** [oscarlab/graphene#2033] opened 2020-12-17 06:39 UTC
Hello, I used the latest version of Graphene with DCAP driver, SDK and PSW for ECDSA Attestation.I built Graphene with DCAP driver support and enabled ECDSA Attestation with `sgx.remote_attestation=1`

I get this error 

```
aesm_service returned error: 30
load_enclave() failed with error -1 
```

Further, when I tried running the QuoteGeneration example in DCAP GitHub repository, I got the error 

```
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent: 
set the enclave load policy as persistent: succeed!
Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe044
```

I also raised an issue in https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/150.

Any ideas on how I could resolve the issue?

**Comment by dimakuv** [comment] 2020-12-17 08:23
Yes, this is not a Graphene problem. It is a problem of SGX DCAP software.

Unfortunately, I am not sure why this issue can happen. Obvious things to check:
1. Is your CPU SGX-enabled and FLC-enabled (Flexible Launch Control)?
2. Is your CPU registered by the Intel PCS (Provisioning Certification Service)?
3. Do older versions of Intel SGX DCAP software stack work on your machine?
4. Do you see any suspicious output in `dmesg` and `sudo service aesmd status`?

**Comment by mkow** [comment] 2020-12-24 01:59
The problem is unrelated to Graphene, closing.

**Closed by mkow** 2020-12-24 01:59 UTC

**Comment by yanzhichao** [comment] 2021-02-07 08:06
I get same error when i try  `SGX=1 ./pal_loader ./pytorch pytorchexample.py ` with End-To-End Confidential PyTorch Workflow guid .but it is no problem when i try the same command with Executing PyTorch with Graphene in SGX Enclave guid.  is there something different in lanch  enclave phase when enable the `sgx.remote_attestation=1` ?

by the way
Does anybody know where I can find the logs about aesmd service ?

**Comment by dimakuv** [comment] 2021-02-07 21:15
To understand how to enable logging in the AESMD service, check https://github.com/intel/linux-sgx/issues/569. Basically, if you want more logs than reported via `service aesmd status`, then you'll need to build the AESMD service in the debug mode.

Yes, there is a difference in enclave startup in Graphene with `sgx.remote_attestation = 1`. Graphene notices that the SGX enclave will use remote attestation and performs an additional initialization step -- Graphene establishes a communication channel with AESMD and asks for AESMD's Quoting Enclave's metadata. If you want to look at the sources, please check:
- https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/quote/aesm.proto
- https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_platform.c#L126

**Comment by yanzhichao** [comment] 2021-03-09 07:58
Thanks for your guidance。 
I  rebuild the AESMD in debug mode ,and also I read the code which you given. Unfortunately I still cann't check out the problem, as there is so less debug information.

Now, I  doubt my platform or the version of Linux-sgx  incompatible with Graphene.
My platform is intel  NUC7PJYH with Intel(R) Pentium(R) Silver J5005 CPU
Here is the cpuid 
```
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = true
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = true
   SGX attributes (0x12/1):
   SGX EPC enumeration (0x12/n):
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = true
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = true
   SGX attributes (0x12/1):
   SGX EPC enumeration (0x12/n):
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = true
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = true
   SGX attributes (0x12/1):
   SGX EPC enumeration (0x12/n):
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = true
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = true
   SGX attributes (0x12/1):
   SGX EPC enumeration (0x12/n):
```

and  the version of Linux-SGX is 2.12 with  following verison of driver and sdk

sgx_linux_x64_driver_1.36.2.bin | 37.7 KiB | 2020-Nov-05 09:03
-- | -- | --
sgx_linux_x64_sdk_2.12.100.3.bin | 16.7 MiB | 2020-Nov-05 09:03

can you tell me  which verison of linux-sgx can be supported for  End-To-End Confidential PyTorch Workflow ？

**Comment by dimakuv** [comment] 2021-03-09 12:20
@yanzhichao The problem is not with Graphene, the problem is with the DCAP library.

In other words, you first need to solve this problem: https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/150.

Graphene developers are separate from Intel DCAP library developers, so we can't help in resolving Intel DCAP issues, unfortunately :(

**Comment by yanzhichao** [comment] 2021-03-10 03:16
Thanks a lot.   
I agree the problem is not with Graphene.  
Actually，different with @kamathhrishi  ,in my platform there is no  problem of intel/SGXDataCenterAttestationPrimitives#150. 

I can run the QuoteGenerationSample successfully  as follow：
```
[get_qpl_handle ../qe_logic.cpp:247] Found the Quote's dependent library. /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1
[get_platform_quote_cert_data ../qe_logic.cpp:336] Found the sgx_ql_get_quote_config and sgx_ql_free_quote_config API.
[get_platform_quote_cert_data ../qe_logic.cpp:337] Request the Quote Config data.
[get_qpl_handle ../qe_logic.cpp:247] Found the Quote's dependent library. /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1
[get_platform_quote_cert_data ../qe_logic.cpp:336] Found the sgx_ql_get_quote_config and sgx_ql_free_quote_config API.
[get_platform_quote_cert_data ../qe_logic.cpp:337] Request the Quote Config data.
[ecdsa_get_quote ../qe_logic.cpp:2068] Call QE3 gen_quote
[ecdsa_get_quote ../qe_logic.cpp:2093] Get quote success
Step4: Call sgx_qe_get_quote:succeed!cert_key_type = 0x5
sgx_qe_cleanup_by_policy is valid in in-proc mode only.

 Clean up the enclave load policy:succeed!

```

It's very probably a problem with my configuration or version.   

so could you tell me which version of linux-sgx you are use ?

**Comment by dimakuv** [comment] 2021-03-10 07:28
> Actually，different with @kamathhrishi ,in my platform there is no problem of intel/SGXDataCenterAttestationPrimitives#150.

Ah, ok. Sorry, I thought that you had an identical problem.

Then I have a couple of suggestions for you:
- Please try `SGX_AESM_ADDR=1` environment variable when running Graphene, see e.g.: https://github.com/oscarlab/graphene/issues/2062#issuecomment-769855356
- For more info on `SGX_AESM_ADDR`, please check https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/107

Another avenue to explore is to follow the official SGX DCAP installation guide from here: https://software.intel.com/content/www/us/en/develop/articles/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html 

Please inform us if any of these help. Currently, correctly installing and using SGX remote attestation + DCAP + Graphene is a bit of a challenge. I will be grateful to know what steps helped you to run stuff. (Unfortunately, it is a bit of a trial-and-error process right now.)

**Comment by yanzhichao** [comment] 2021-03-19 13:37
What a Suggestions，It works！
Although I still can't find the root cause of the problem, but it works!
I share my works as follow:

### Hardware platform:
`Intel NUC7PJYH with Intel(R) Pentium(R) Silver J5005 CPU`
the sgx information:
```
root@chase:~/graphene/Pal/src/host/Linux-SGX/tools/is-sgx-available# ./is_sgx_available 
SGX supported by CPU: true
SGX1 (ECREATE, EENTER, ...): true
SGX2 (EAUG, EACCEPT, EMODPR, ...): true
Flexible Launch Control (IA32_SGXPUBKEYHASH{0..3} MSRs): true
SGX extensions for virtualizers (EINCVIRTCHILD, EDECVIRTCHILD, ESETCONTEXT): false
Extensions for concurrent memory management (ETRACKC, ELDBC, ELDUC, ERDINFO): false
CET enclave attributes support (See Table 37-5 in the SDM): false
Key separation and sharing (KSS) support (CONFIGID, CONFIGSVN, ISVEXTPRODID, ISVFAMILYID report fields): false
Max enclave size (32-bit): 0x80000000
Max enclave size (64-bit): 0x1000000000
EPC size: 0x5e00000
SGX driver loaded: true
SGX PSW/libsgx installed: true
AESMD running: true
```
Operate System：Ubuntu 18.04

### The steps to run the stuff successful
+ 1、clean the environment，use `apt purge` to clean the package about sgx you have installed before.
+ 2、install the DCAP driver and SDK:`https://download.01.org/intel-sgx/sgx-linux/2.12/distro/ubuntu18.04-server/` with the version :`sgx_linux_x64_driver_1.36.2.bin` and `sgx_linux_x64_sdk_2.12.100.3.bin`
+ 3、build the linux-sgx aes by yourself  follows this guide：`https://github.com/intel/linux-sgx`  in Build the Intel(R) SGX PSW and Intel(R) SGX PSW Installer . version: linux-sgx 2.12 with SGXDataCenterAttestationPrimitives 1.9
```
$ cd psw/ae/le
$ make deb_psw_pkg
```
 Install the all the deb packages manual

+ 4、Run the SampleCode of SGXDataCenterAttestationPrimitives 1.9
`https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/SampleCode/QuoteGenerationSample`
here is something strange，you must make the ` out-of-proc` mode success  as  `SGX_AESM_ADDR=1 ./app`

+ 5、build the Graphene 

+ 6、Finally，I run the stuff successful  with End-To-End Confidential PyTorch Workflow guid .You may need  add ` loader.pal_internal_mem_size = "512MB"` to the  manifest file

### Some analysis
+ 1、At beginning，I install the linux-sgx for dcap  use `apt install`  follow  the guide:`https://software.intel.com/content/www/us/en/develop/articles/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html`， I get the same error as same as @kamathhrishi issuse,  I read the source code in linux-sgx ，the error of aesm_service returned error: 30  is `AESM_SERVICE_UNAVAILABLE` ，it means when the graphene get the quote information through aesmd service ，the aesmd is unavailable。  
so I guess the linux-sgx is not installed correctly. I find that use `apt install` to  install the linux-sgx will get mixed version in components ，so I suspect that it will cause the error. 
I suggest build the linux-sgx by yourslef so you can keep the version of components same.

+ 2、As above suggest  I build the  linux-sgx by myself with the verison 2.12 ,and manually install the components 。 Then I run the SampleCode of SGXDataCenterAttestationPrimitives successfully with the in-of-proc .  I thought I made it ,but Unfortunately I still get the error when I run the Graphene PPML,  but the error code from the aesm_service become  1

+ 3 At last I run the SampleCode of SGXDataCenterAttestationPrimitives with out-of-proc again ,it run successful.  And then ,I run the PPML again ,it successful.  
Why ? I can't find the cause. But I guess the default mode of DCAP will only do local attestion, so it don't cache the PCK in the local database.  So when Graphene get the quote through the aesmd will make mistake.  When do the SampleCode of DCAP with out-of-proc , it cache the PCK in the local database ,so the follow-up is working.

**Comment by dimakuv** [comment] 2021-03-23 14:20
Great to hear that you solved this! I really appreciate describing the steps you made, thanks :)
