### ISSUE TITLE
Apache httpd in HTTPS

### ISSUE THREAD

**Issue by andreluis034** [oscarlab/graphene#1215] opened 2019-12-17 17:50 UTC
I'm trying to utilize HTTPS with the apache example/test provided in the [test repository](https://github.com/oscarlab/graphene-tests/tree/dfb8e3abf10e9cdbb4c74647d288140b70abd983/apache).

I'm able to compile and utilize HTTP normally with httpd running under graphene-sgx  the application.

To test HTTPS I uncommented the following lines in httpd.conf:

- LoadModule ssl_module modules/mod_ssl.so
- Include conf/extra/httpd-ssl.conf

Additionally I commented the option SSLSessionCache in extra/httpd-ssl.conf and edited the vhost accordingly to point to my certificate and key.

I've also added my key, cert and httpd-ssl.conf in the httpd.manifest.template

I've also noticed that unless I specify the argument `-C "Listen 127.0.0.1:4433"` to the pal_loader, when I try connecting to the same port I get a connection refused even though the same directive is specified in httpd-ssl.conf. Why is this required?

Although probably unnecessary I've uploaded the modified files to a [gist](https://gist.github.com/andreluis034/83216231c7ce2da3438b327242cee39d)

I can confirm HTTPS is working when ran natively with `make start-native-server`

But when ran with graphene with `make start-graphene-server` it looks like HTTPS is not enabled: 

[Native and graphene-sgx outputs](https://gist.github.com/andreluis034/0277acfc773710c88ea8d464f2ec19d8)

After enabled HTTPS via the aforementioned method when I send a SIGINT (Ctrl+C) to the application, apache stops and the console fills with repeating messages about the signal queue being full:
`
signal queue is full (TID = 2, SIG = 11)
signal queue is full (TID = 3, SIG = 11)
signal queue is full (TID = 4, SIG = 11)
signal queue is full (TID = 5, SIG = 11)
`
and the [error_logs of apache](https://github.com/oscarlab/graphene/files/3974607/error_log.txt) specify that the child processes did not exit.

To terminate the processes I have to send a SIGKILL signal to the pal-loader processes

**Comment by dimakuv** [comment] 2019-12-17 23:57
Hi @andreluis034,

Thanks for the great description, I really appreciate that you sent the logs and your files!

It looks like the root cause is: `[Tue Dec 17 17:29:22.188131 2019] [unixd:alert] [pid 5] (2)No such file or directory: AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive`.

So, if you do `man getpwuid` (and/or google it), you'll notice that for this Glibc tries to access special files: `/etc/passwd` and `/etc/nsswitch.conf`. What this means for Graphene:
1. You need to mount the corresponding `/etc` mount point in your manifest, and
2. You need to white-list the required files (for SGX).

Please refer to the example of https://github.com/oscarlab/graphene-tests/blob/master/memcached/memcached.manifest.template.

Please add this stuff in the manifest and rebuild everything. In case of further problems, write back here.

**Comment by andreluis034** [comment] 2019-12-18 20:44
Hi @dimakuv,

Mounting etc and whitelisting the files was not sufficient to solve the warning. I had to uncomment the User and group directive in the httpd-graphene.conf file(which the makefile comments). The warning appears even if you just clone the repository and run it so it seems unrelated to the HTTPS issue?

Unfortunately the issue seems to persist. I've seen in issue #1092 that apache does use MSG_PEEK once in its code base, but I'm unsure if this code somehow relates to the mod_ssl module. Could this be the cause?

**Comment by dimakuv** [comment] 2019-12-18 20:51
Ah, ok, then scratch my comment. If the warning appears even in non-HTTPS mode and Graphene still runs, then it's not the root cause.

Yep, it well can be that `recv(..., MSG_PEEK)` is the culprit. One way to debug is to do `strace -ff ./httpd ...` on the original Apache with HTTPS and observe if this run spits a syscall with `MSG_PEEK` (one of the `recv/recvmsg/recvfrom`). If yes, then we know that this is the problem.

If there is indeed `MSG_PEEK`, then you can:
1. Track the status of PR https://github.com/oscarlab/graphene/pull/1110 and wait till it's merged, and then try Apache again.
2. Try this PR locally and see if it solves your issue. Please report the result if you try it.

**Comment by andreluis034** [comment] 2019-12-19 00:40
Apache seems to use recvmsg rather than recv and the flags parameter is always 0, they do not seem to use MSG_PEEK.

**Comment by dimakuv** [comment] 2020-01-15 02:34
@andreluis034 If it is still relevant, you can try the following PR: #1253. Maybe it will fix your failures (though as you mention, the root cause seems to be different).

**Comment by andreluis034** [comment] 2020-01-26 23:19
Sorry for the delay on the testing. I have tested both the PR and the commit 2e4d929c5b0a4b5bef90e6e4adfec0dea8d6a8fd on master(latest as of 2020/01/26) the result is the same. Attempting to connect to the https vhost, through curl, results in 'SSL_ERROR_SYSCALL'

I've also noticed when loading the mod_ssl but not enabling HTTPS I am no longer able to exit httpd gracefully(i.e. through CTRL+C), as it results in the aforementioned issue regarding the signal queue being full.

**Comment by dimakuv** [comment] 2020-01-27 18:16
@andreluis034 Thanks for this. I'll debug your workload today, let's see what kind of bugs you hit in Graphene. Thanks for putting config/manifest files on gist!

**Comment by dimakuv** [comment] 2020-01-28 03:04
@andreluis034 Check out these PRs:

- https://github.com/oscarlab/graphene-tests/pull/68
- https://github.com/oscarlab/graphene/pull/1276
- https://github.com/oscarlab/graphene/pull/1277

I just uploaded them, there can still be issues. But it worked on my machine locally.

**Comment by andreluis034** [comment] 2020-01-29 16:12
I'm still facing the same issue. When making a request to the https vhost: curl -k https://127.0.0.1:8443

As I started doubting my machine I've updated sgx's driver, psw and sdk. But the issue persists.

To test the PR I checked out to the dimakuv/add-apache-with-ssl branch and compiled it from scratch, by following the steps in the [wiki](https://github.com/oscarlab/graphene/wiki) up until 2.1.3(inclusive) and then running apache as mentioned in [the corresponding wiki page](https://github.com/oscarlab/graphene/wiki/Run-Applications-in-Graphene-SGX).

The head commits seem to match those of https://github.com/oscarlab/graphene-tests/pull/68 :
graphene: 3d6faf99601fdf587f909cdf3e233de7db849743
test-apps: 73992d550f5c7e65a9c2db6ed0f6485a811dc7ba
sgx-driver: 30d4b9400afb5fd78c600717340d6883ea128dd4

Although probably unrelated, the hardware I am testing this on is running Ubuntu 18.04 LTS with an i7-6770HQ

**Comment by dimakuv** [comment] 2020-01-29 16:26
https://github.com/oscarlab/graphene/pull/1276 -- could you also apply this patch? Shouldn't be that relevant though (for the updated Apache example, I hardcoded IPv4 address 127.0.0.1).

Also, do `ab ...` and `wget` as described in the README of the example work? Do you experience problems only with `curl`?

**Comment by andreluis034** [comment] 2020-01-29 18:06
Ah sorry, I somehow missed #1276 . Having tested it, the end result is the same
`ab https://127.0.0.1:8443` results in SSL handshake failed(5)
`curl -k https://127.0.0.1:8443/` results in `curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8443`
`wget --no-check-certificate https://127.0.0.1:8443/` results in `Connecting to 127.0.0.1:8443... connected.
Unable to establish SSL connection.`

Firefox gives a 'Secure Connection Failed' PR_END_OF_FILE_ERROR

**Comment by dimakuv** [comment] 2020-01-29 18:15
That's bizarre... It works on my local machine and it works on our Jenkins machines (including Ubuntu 18.04). Are you sure you correctly run `SGX=1 make start-graphene-server`? Did you modify anything?

**Comment by andreluis034** [comment] 2020-01-29 18:36
Oh this is embarrassing... I was not including the SGX=1 environment variable when executing the server. I assumed this was not needed as in the [wiki](https://github.com/oscarlab/graphene/wiki/Run-Applications-in-Graphene-SGX#running-apache-in-graphene) it is only mentioned for compilation.

**Comment by mkow** [comment] 2020-01-29 19:46
Yeah, seems like a bug in our old documentation. We're moving away from GitHub Wiki to ReadTheDocs right now and it seems the problem [was already fixed there](https://graphene.readthedocs.io/en/latest/oldwiki/Run-Applications-in-Graphene-SGX.html#running-apache-in-graphene-sgx). After merging #1273 we'll disable the Wiki and point everyone to RTD.

**Comment by dimakuv** [comment] 2020-01-29 22:00
@andreluis034 We seem to reproduce your issue with *non-SGX* Graphene on Ubuntu 18.04. I will debug this version.

But yes, you should use `SGX=1 ...` to work on SGX version of Graphene. Which I assume what you want anyway.

**Comment by dimakuv** [comment] 2020-02-05 22:31
We found the bug and fixed it in this PR: https://github.com/oscarlab/graphene/pull/1293. We also updated Apache example with HTTPS: https://github.com/oscarlab/graphene-tests/pull/68. Both PRs are merged in the master branch.

I am closing this issue.

**Closed by dimakuv** 2020-02-05 22:31 UTC
