### ISSUE TITLE
Support for netlink sockets

### ISSUE THREAD

**Issue by sudharkrish** [oscarlab/graphene#2250] opened 2021-03-18 01:10 UTC
## Description of the problem
Currently graphene does not support netlink sockets.
Working on a project, that needs support for netlink sockets to communicate with kernel.
Project info here-> https://github.com/omec-project/upf-epc
Would like to know, if there is any plan to support netlink socket in graphene.

## Steps to reproduce
When running any application, that creates netlink socket, for example:
socket(PF_NETLINK, SOCK_RAW, 0);
fails with error(-1) returned by graphene(since it is not supported).

### PLEASE ENSURE THAT THE ISSUE REPRODUCES ON THE CURRENT MASTER BRANCH ###

-->

**Comment by mkow** [comment] 2021-03-18 02:22
Isn't this a duplicate of #1995?

**Comment by sudharkrish** [comment] 2021-03-19 22:08
Yes @mkow, you can close this one. Also, if you are aware of any plans to support this, you can update in the other PR.

**Closed** 2021-03-20 01:17 UTC
