### ISSUE TITLE
Run graphene-sgx ./pytorch ./test.py has errors related to pycache/future.cpython-38.pyc.1110420480

### ISSUE THREAD

**Issue by bliu40** [oscarlab/graphene#2565] opened 2021-07-20 21:28 UTC
The graphene has been built successfully on the ubuntu 20.04 server, I try to run some inference programs ($graphene-sgx ./pytorch inference.py) under the path: ~graphene/Examples/pytorch/,  it has errors as following:

error: Could not find size of file: file:/usr/lib/python3.8/__pycache__/__future__.cpython-38.pyc.1110420480
error: Failed to load the checksums of trusted files: -6

If I use $sudo graphene-sgx ./pytorch inference.py, the errors are changed:

error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
error: Forwarding host environment variables to the app is enabled. Graphene will continue application execution, but this configuration must not be used in production!
Traceback (most recent call last):
  File "./inference.py", line 1, in <module>
    import torch
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 980, in get_code
  File "<frozen importlib._bootstrap_external>", line 1037, in get_data
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/torch/__init__.py'

I am so confusing, how to fix that? Thanks in advance.

**Comment by bliu40** [comment] 2021-07-21 03:19
![image](https://user-images.githubusercontent.com/12901110/126425360-c773a7ea-3eb0-41e3-ae9f-7dd19f183784.png)

**Comment by dimakuv** [comment] 2021-07-21 07:37
You're doing something wrong with user permissions. How do you install Graphene? Why do you try `sudo`?

In general, Python workloads should *never* be run under sudo.

**Comment by mkow** [comment] 2021-07-21 14:16
@bliu40 also, please don't post logs as screenshots...

**Comment by bliu40** [comment] 2021-07-21 17:58
> @bliu40 also, please don't post logs as screenshots...

Sure, I delete that. This is my first time to post the issue, please correct me if I have done something wrong.

**Comment by mkow** [comment] 2021-07-21 18:32
Thanks. The problem with screenshots is that you can't copy or search text in them, plus they are pretty heavy compared to text. You can paste logs (if they aren't too long) using proper Markdown syntax for them (triple backticks).

**Comment by bliu40** [comment] 2021-07-21 20:26
> triple backticks

Sure, thanks for letting me know.

**Comment by bliu40** [comment] 2021-07-21 20:26
> Thanks. The problem with screenshots is that you can't copy or search text in them, plus they are pretty heavy compared to text. You can paste logs (if they aren't too long) using proper Markdown syntax for them (triple backticks).

Sure, thanks for letting me know.

**Comment by bliu40** [comment] 2021-07-21 20:30
> You're doing something wrong with user permissions. How do you install Graphene? Why do you try `sudo`?
> 
> In general, Python workloads should _never_ be run under sudo.

Thanks for the reply. If I do not use the "sudo", I will get the error:

**Actual results:**

error: Could not find size of file: file:/usr/lib/python3.8/pycache/future.cpython-38.pyc.1110420480
error: Failed to load the checksums of trusted files: -6


Any idea how to handle this issue? thanks in advance

**Comment by dimakuv** [comment] 2021-07-22 07:20
This is a duplicate of your other issue #2564 (the underlying issue is the same), so let's close this issue and keep the discussion in #2564.

**Closed by dimakuv** 2021-07-22 07:20 UTC
