### ISSUE TITLE
support out of source tree build

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#377] opened 2018-12-10 22:19 UTC
to allow build of multiple configuration cleanly.
This will apply not only pal (e.g. with/without SGX), but also for exmaple, multiple libc versions.

**Comment by mkow** [comment] 2018-12-12 02:02
We definitely need this change, the problem is annoying for everyone.

We've already discussed this problem on Slack with @chiache and were considering migration to CMake at some point. We don't want to do this right now because of problems with tests stability and other high-priority issues, but we plan to revisit this afterwards.

**Comment by dimakuv** [comment] 2021-07-14 09:07
We are in the middle of migration to Meson which forces to have out-of-source-tree builds. Given that this is already the case even with our current half-way Meson build system, I'm closing this issue.

**Closed by dimakuv** 2021-07-14 09:07 UTC
Labels: enhancement, feature request
