### ISSUE TITLE
fstat03 didn't reported results when executed in Graphene OS

### ISSUE THREAD

**Issue by anjalirai-intel** [oscarlab/graphene#2256] opened 2021-03-19 12:51 UTC
## Testfile
fstat03

## Description of the problem
The testfile has 2 testcases checking for error EBADF and EFAULT. In Graphene OS, 1 testcase is passed and 2nd one does not returns result and throws error. Error handling is not done properly

## Expected results
root@ubuntu-test-base: ./fstat03
/root/MasterGraphene/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
TPASS: fstat() fails with expected error EBADF
TPASS: fstat() fails with expected error EFAULT

Summary:
passed   2
failed   0
skipped  0
warnings 0

## Actual results
root@ubuntu-test-base: ./pal_loader fstat03
WARNING: Using insecure argv source. Don't use this configuration in production!
TINFO: Timeout per run is 0h 05m 00s
TPASS: fstat() fails with expected error EBADF
TBROK: Test 0 haven't reported results!

Summary:
passed   0
failed   0
skipped  0
warnings 0

**Comment by dimakuv** [comment] 2021-07-12 06:12
@aneessahib will work on this bug. Anees, please comment here (with any text), because only commenters on issues can be put into "Assignees".

**Comment by aneessahib** [comment] 2021-07-12 06:15
Able to repro the issue. debugging this now.

**Comment by aneessahib** [comment] 2021-09-01 04:20
```
		if (results_equal(&saved_results, results))
			tst_brk(TBROK, "Test %i haven't reported results!", i);
```
```results``` is a global variable. Updates from child does not reflected due to no support for shared memory. This is expected behavior for now.

**Comment by mkow** [comment] 2021-09-01 06:02
This test is already disabled in our config (exactly for this reason), so I'll just close this issue.

**Closed by mkow** 2021-09-01 06:02 UTC
Labels: bug, P: 1
