### ISSUE TITLE
Pal/Linux and Pal/Linux-SGX should share code of db_*.c

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#443] opened 2019-01-27 19:25 UTC
db_*.c of Pal/Linux and Pal/Linux_SGX are mostly same and the difference is only host syscall or ocall.
Because they are maintained differently, there are several bugs in only one of them with other fixed.
this is very bad situation. we should consolidate them into one to reduce maintenance cost and to increase test coverage.

**Comment by donporter** [comment] 2019-01-28 20:23
I agree with this.  It would be good to hoist more similar code that has a common function into a shared code base.

**Comment by mkow** [comment] 2019-02-19 14:13
+1, this is definitely a huge problem with our current codebase.

**Comment by dimakuv** [comment] 2019-10-18 18:56
Just to add to this, I recently submitted a PR #1091 which re-writes the threading of SGX PAL to closely resemble the threading of Linux PAL. So the PR on sharing of code should be done after #1091 is merged.

**Comment by dimakuv** [comment] 2021-07-14 09:53
Duplicate of #895. Let's close this issue and track all progress in #895.

**Closed by dimakuv** 2021-07-14 09:53 UTC
Labels: future plans
