### ISSUE TITLE
Unable to run Mariadb server application with SGX

### ISSUE THREAD

**Issue by sindhuamir** [oscarlab/graphene#2221] opened 2021-03-09 06:43 UTC
## Description of the problem

Unable to run Mariadb application with Graphene LibOS

## Steps to reproduce

Issue produced on Graphene repo with latest commit below:

commit d97f43a4cce4fc5c7f35d064f701e9afc2a538d2 (HEAD -> dimakuv/init-log-level-in-enclave-early, origin/dimakuv/init-log-level-in-enclave-early)
Author: Dmitrii Kuvaiskii <dmitrii.kuvaiskii@intel.com>
Date:   Tue Mar 2 00:02:20 2021 -0800

    [Pal] Set default log level early in enclave init

    Previously, `g_pal_control.log_level` was not explicitly initialized,
    so it was set to `0` which didn't print any log messages during early
    init phase (before parsing the manifest `log_level` setting).

    Signed-off-by: Dmitrii Kuvaiskii <dmitrii.kuvaiskii@intel.com>

- Attached are the mariadb manifest template, Make file & sgx & non sgx manifest files. Command used to run the mariadb application:

SGX=0 ./pal_loader mysqld -uroot --innodb_use_native_aio=0 --log-bin 
SGX=1 ./pal_loader mysqld -uroot --innodb_use_native_aio=0 --log-bin 

- mysqld --version
mysqld  Ver 10.3.28-MariaDB-1:10.3.28+maria~bionic for debian-linux-gnu on x86_64 (mariadb.org binary distribution)

- VERSION="18.04.5 LTS (Bionic Beaver)", 5.9.0-rc5-intel-next+

[mysqld.manifest.sgx.txt](https://github.com/oscarlab/graphene/files/6106352/mysqld.manifest.sgx.txt)
[mysqld.manifest.txt](https://github.com/oscarlab/graphene/files/6106353/mysqld.manifest.txt)
[mariadb_graphene_failing.log](https://github.com/oscarlab/graphene/files/6106335/mariadb_graphene_failing.log)

[Makefile.txt](https://github.com/oscarlab/graphene/files/6106344/Makefile.txt)
[mysqld_manifest_template.txt](https://github.com/oscarlab/graphene/files/6106345/mysqld_manifest_template.txt)

## Expected results

In passing case mysqld application should be created successfully and executing client command should connect to the application.:
 
mysql -uroot --protocol=tcp -P 9900 -p

## Actual results

[mariadb_graphene_failing.log](https://github.com/oscarlab/graphene/files/6106338/mariadb_graphene_failing.log)

**Comment by mkow** [comment] 2021-03-09 11:55
Some of the errors are related to the fact we don't support file locks yet (but we plan to do this as part of #1803), but it seems to continue despite them.

```
2021-03-08 22:24:17 0 [ERROR] mysqld: Can't lock aria control file '/var/lib/mysql/aria_log_control' for exclusive use, error: 38. Will retry for 30 seconds
```

(38 is ENOSYS, which is expected, because we don't implement these syscalls)

The fatal error seems to be this one:
```
2021-03-08 22:26:28 0 [ERROR] InnoDB: Cannot open datafile './ibdata1'
```

Most likely the problem is that you didn't add this file to allowed_files not trusted_files. If you change Graphene log_level to "warning" or below, you should see a warning that an access was refused due to this.

btw. I'm not sure from your description if the failure is the same on both SGX and non-SGX, if it fails on non-SGX also, then it means that MariaDB actually requires the locking and doesn't fall back to any other mechanism in case of ENOSYS.

**Comment by dimakuv** [comment] 2021-03-09 12:45
For what it's worth, I'm fairly certain that MySQL (used underneath MariaDB? not sure what is the dependency here) **requires** file locking, and loudly fails when it doesn't detect this feature. Which is not implemented in Graphene.

**Comment by mkow** [comment] 2021-07-12 23:51
@sindhuamir please try again on current master, we implemented POSIX locks recently.

**Comment by dimakuv** [comment] 2021-07-22 09:27
@sindhuamir Please try again on the current master. Otherwise we'll close this issue shortly, assuming it was resolved.

**Comment by mkow** [comment] 2021-07-22 21:43
Nah, I'll just close it :) There was no reply since March here and the issue is almost for sure already resolved.
@sindhuamir please reopen/ping us if the problem still persists.

**Closed by mkow** 2021-07-22 21:43 UTC
