### ISSUE TITLE
Fork not working with sh with Graphene Shielded container

### ISSUE THREAD

**Issue by manojgop** [oscarlab/graphene#1569] opened 2020-06-10 10:32 UTC
## Description of the problem
A sample C++ program which calls fork crashes with message "Killed" when running in Graphene shielded container (PR: [https://github.com/oscarlab/graphene/pull/1430]) if we use "sh" in Dockerfile eg: CMD [“sh”, “-c”, “cpptest”] 

## Steps to reproduce
1) Build docker image (cpptest) in attached sample application 
2) Build GSC docker image : sudo ./gsc build cpptest test/sh.manifest test/cpptest.manifest
3) Run GSC docker image:  sudo docker run -it --device=/dev/gsgx --device=/dev/isgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-cpptest

## Expected results
gsc based docker application which calls fork() should work without crashing with below CMD in dockerfile
_CMD [“sh”, “-c”, “cpptest”]_

## Actual results
GSC Application crashes in container with "Killed" message in stdout
[cpptest.zip](https://github.com/oscarlab/graphene/files/4757861/cpptest.zip)
[gsc-mycpptest.log.zip](https://github.com/oscarlab/graphene/files/4757867/gsc-mycpptest.log.zip)

1) _CMD [“sh”, “-c”, “cpptest”]_ -> gsc image run crash with “Killed”
GSC build command: sudo ./gsc build cpptest test/sh.manifest test/cpptest.manifest

2) If we remove sh and directly run sample application which calls fork() it works
_CMD [“cpptest”]_ - works. No crash. 
GSC build command: sudo ./gsc build cpptest test/bash.manifest test/cpptest.manifest

3) If we replace sh with bash and run sample application which calls fork() it works
_CMD [“bash”, “-c”, “cpptest”]_  - works. No crash. 
GSC build command: sudo ./gsc build cpptest test/bash.manifest test/cpptest.manifest

**Comment by manojgop** [comment] 2020-06-19 12:04
Update: After I reduce the SGX enclave Size from 4G to 256M it works fine.
sgx.enclave_size = 256M --> works fine
sgx.enclave_size = 4G ---> crashes

**Comment by dimakuv** [comment] 2020-06-22 18:20
@manojgop I do not see any errors in the attached `gsc-mycpptest.log.zip`. Is this the complete log?

The error you experience is weird. I cannot find a reason why it would fail with 4GB but succeed with 256MB. Could it be that your Linux machine simply doesn't have enough RAM, and Linux decides to kill this application? (Linux has an OOM killer: https://unix.stackexchange.com/questions/153585/how-does-the-oom-killer-decide-which-process-to-kill-first).

**Comment by manojgop** [comment] 2020-06-23 10:36
@dimakuv I'm able to reproduce this issue using standalone graphene SGX (without GSC). Attached is the sample cppexec code. You can try it by unzipping it in Examples folder.  `make SGX=1` and run using `SGX=1 ./pal_loader cppexec.manifest` . 
If I keep `sgx.enclave_size = 4G`  process gets killed with `sgx.enclave_size = 256M` it's working.

I'm trying this in Azure VM. 
MemTotal:       16397588 kB
MemFree:         9250012 kB
MemAvailable:   11218596 kB

[cppexec.zip](https://github.com/oscarlab/graphene/files/4818797/cppexec.zip)

**Comment by boryspoplawski** [comment] 2021-01-15 19:41
@manojgop Could you try the current master? I was unable to reproduce the issue. Note that the manifest handling changed, see examples for more information.

**Comment by mkow** [comment] 2021-07-12 23:36
No reply from the reporter, closing. @manojgop feel free to reopen if the issue still occurs on the current master.

**Closed by mkow** 2021-07-12 23:36 UTC
