### ISSUE TITLE
[LibOS] `/proc` is broken

### ISSUE THREAD

**Issue by pwmarcz** [oscarlab/graphene#2385] opened 2021-05-19 13:54 UTC
## Description of the problem

Several things in `/proc` do not work correctly:
- other processes than self
- `/proc/xxx/fd`
- `/proc/xxx/task/`

## Steps to reproduce

Go to `busybox` example and try to run:

```graphene-direct sh -c 'sleep 1 & find /proc```

## Expected results

```
/proc
/proc/self
/proc/self/cwd
/proc/self/exe
/proc/self/root
/proc/self/fd
/proc/self/fd/1
...
/proc/self/maps
/proc/self/task
/proc/self/task/1
...
/proc/self/cmdline
/proc/1
...
/proc/1/cmdline
/proc/2
...
```

## Actual results

Several files are inaccessible:

```
find: /proc/self/fd: Permission denied
find: /proc/self/task/1: Not a directory
find: /proc/1/fd: Permission denied
find: /proc/1/task/1: Not a directory
find: /proc/2: Permission denied
```

## Additional information

There needs to be a more comprehensive test for this.

**Comment by pwmarcz** [comment] 2021-05-19 13:56
Assigning to myself since I'm working of filesystem refactoring now.

**Comment by boryspoplawski** [comment] 2021-05-22 00:25
Duplicate of #948 ?

**Closed** 2021-06-28 06:20 UTC
