### ISSUE TITLE
Running dotnet app in SGX

### ISSUE THREAD

**Issue by pedrotbtl** [oscarlab/graphene#1918] opened 2020-10-26 17:49 UTC
Hi,

First of all, thanks for creating such a great framework!

I am new to graphene and I am trying to run a dotnet application inside it. I created a zip at [link](https://drive.google.com/file/d/1xnndiP04HtTqU1MEu3bCtQnVU7xmnSnJ/view) with a hello world project which I am trying to run in SGX mode.

"hello" is a binary that bundles the dotnet runtime + a hello world app. I built it with: 

``dotnet publish -r linux-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true --self-contained true``

and the source code is at [myApp.zip](https://github.com/oscarlab/graphene/files/5440459/myApp.zip)

There seems to be an error due to the how graphene handles /proc/self/exe. Is there any workaround? Could you help me figure out how to run this application in SGX mode?

I am on Ubutu 18.04 and using dotnet 3.1. 

Many thanks in advance,

Pedro

**Comment by mkow** [comment] 2020-10-27 00:20
Hi,

I don't know about any easy workaround for this. Unfortunately the procfs support in Graphene is currently very minimal, moreover, symlinks support is heavily broken and most likely will need to be fixed before implementing procfs symlinks.

**Comment by dimakuv** [comment] 2021-07-22 10:17
@pedrotbtl We added extensive support for `/proc` in the recent months. Please try again on the latest Graphene. Otherwise I will close this issue after a couple days, assuming the issue is resolved.

**Comment by pedrotbtl** [comment] 2021-07-22 13:40
@dimakuv Thanks very much for the heads up. I will give it a go and get back to you, probably no so quickly! Thanks a lot!

**Comment by mkow** [comment] 2021-08-31 15:17
@pedrotbtl: Any updates on this? Can we close this issue?

**Comment by pedrotbtl** [comment] 2021-08-31 15:23
Hi @mkow and @dimakuv, I haven't got time to test this yet. Please close it and I follow up with you once I have tested it out. Thanks for implementing this!

**Closed** 2021-08-31 15:25 UTC
