### ISSUE TITLE
Cannot run lscpu in enclave

### ISSUE THREAD

**Issue by mhpanah** [oscarlab/graphene#2004] opened 2020-11-30 17:39 UTC
## Description of the problem

I'm trying to create a GSC in Centos for a python application which uses lscpu. To do so, I created two manifest files.  One for the python and one for lscpu.  Inside the python manifest I included: `sgx.trusted_children.clscpu = "file:/home/graphene/lscpu.sig"`. In the lscpu manifest, I included `kernel_max` file as both trusted and allowed file. (`sgx.trusted_files.kernel_max = "file:/sys/devices/system/cpu/kernel_max"`), however, I'm still getting the error below:

```
Accessing file:/sys/devices/system/cpu/kernel_max is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
Traceback (most recent call last):
  File "/home/graphene/test_lscpu.py", line 8, in <module>
    subprocess.check_output([lscpu_cmd], stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1318, in _execute_child
    part = os.read(errpipe_read, 50000)
PermissionError: [Errno 13] Permission denied
```

Here is  my simple python application file:
```
import os
import subprocess

lscpu_cmd = "lscpu"

try:
    subprocess.check_output([lscpu_cmd], stderr=subprocess.STDOUT)
except subprocess.CalledProcessError as e:
    raise RuntimeError("command '{}' return with error (code {}): {}".format(e.cmd, e.returncode, e.output))
print("Hello LSCPU")
```

**Comment by dimakuv** [comment] 2020-11-30 18:05
You probably forgot to add an FS mount point in the manifest:
```
fs.mount.sysdev1.type = "chroot"
fs.mount.sysdev1.path = "/sys/devices"
fs.mount.sysdev1.uri = "file:/sys/devices"
```

Actually we will have proper `sysfs` emulation soon in Graphene (see https://github.com/oscarlab/graphene/pull/1975). But for now please use this FS mount point.

**Comment by mhpanah** [comment] 2020-11-30 18:52
> You probably forgot to add an FS mount point in the manifest:
> 
> ```
> fs.mount.sysdev1.type = "chroot"
> fs.mount.sysdev1.path = "/sys/devices"
> fs.mount.sysdev1.uri = "file:/sys/devices"
> ```
> 
> Actually we will have proper `sysfs` emulation soon in Graphene (see #1975). But for now please use this FS mount point.

@dimakuv , I do have FS mount point in the manifest. Here are my manifests.  Thanks.

lscpu Manifest

```
#lscpu Manifest

loader.preload = "file:/usr/libexec/graphene/libsysdb.so"

loader.env.LD_LIBRARY_PATH = "/lib:/lib64:/usr/lib64"

loader.debug_type = "none"

# Read application arguments directly from the command line. Don't use this on production!
loader.insecure__use_cmdline_argv = 1

fs.root.type = "chroot"
fs.root.path = "/"
fs.root.uri = "file:/"

fs.mount.lib2.type = "chroot"
fs.mount.lib2.path = "/lib64"
fs.mount.lib2.uri = "file:/lib64"

fs.mount.lib3.type = "chroot"
fs.mount.lib3.path = "/usr/lib64"
fs.mount.lib3.uri = "file:/usr/lib64"

fs.mount.etc.type = "chroot"
fs.mount.etc.path = "/etc"
fs.mount.etc.uri = "file:/etc"

# Mount /tmp
fs.mount.tmp.type = "chroot"
fs.mount.tmp.path = "/tmp"
fs.mount.tmp.uri = "file:/tmp"


fs.mount.sysdev1.type = "chroot"
fs.mount.sysdev1.path = "/sys/devices"
fs.mount.sysdev1.uri = "file:/sys/devices"


fs.start_dir = "/"

# Start at static addresses (otherwise breaks when static and PIE executables are used)
sgx.static_address = 1

# Minimum amount of memory to make it work.
sgx.allow_file_creation = 1
sgx.enclave_size = "512M"
sgx.thread_num = 16


sgx.trusted_files.ld_linux_ = "file:/usr/libexec/graphene/ld-linux-x86-64.so.2"
sgx.trusted_files.libc_ = "file:/usr/libexec/graphene/libc.so.6"

sgx.trusted_files.locale_alias_ = "file:/usr/share/locale/locale.alias"
sgx.trusted_files.gconv_modules_ = "file:/usr/lib64/gconv/gconv-modules"
sgx.trusted_files.gconv_modules_cache_ = "file:/usr/lib64/gconv/gconv-modules.cache"
sgx.trusted_files.libsmartocols_ = "file:/lib64/libsmartcols.so.1"
sgx.trusted_files.ld_cache_ = "file:/etc/ld.so.cache"
sgx.trusted_files.libmartocols_use_ = "file:/usr/lib64/libsmartcols.so.1"
sgx.trusted_files.libs_ = "file:/lib64/libc.so.6"
sgx.trusted_files.libs_usr_ = "file:/usr/lib64/libc.so.6"
sgx.trusted_files.kernel_max = "file:/sys/devices/system/cpu/kernel_max"


sgx.trusted_files.bash_ = "file:/bin/bash"
sgx.trusted_files.uname_ = "file:/bin/uname"

sgx.trusted_files.locale_alias = "file:/usr/share/locale/locale.alias"
sgx.trusted_files.lc_ctype = "file:/usr/lib/locale/C.utf8/LC_CTYPE"

sgx.allowed_files.usr_bin   = "file:/usr/bin"

sgx.trusted_files.date_ = "file:/bin/date"
sgx.trusted_files.bin_tr_ = "file:/bin/tr"

#sgx_allowed_files.kernel_max = "file:/sys/devices/system/cpu/kernel_max"
sgx.allowed_files.lscpu_ = "file:lscpu"
```


Python Manifest:

```
#Python manifest

loader.preload = "file:/usr/libexec/graphene/libsysdb.so"

# Get path of binary
loader.execname = "python3"
loader.env.LD_LIBRARY_PATH = "/lib:/lib64:/usr/lib64"
loader.debug_type =  "none"

fs.mount.lib.type = "chroot"
fs.mount.lib.path = "/lib"
fs.mount.lib.uri = "file:/usr/libexec/graphene/"

fs.mount.lib2.type = "chroot"
fs.mount.lib2.path = "/lib64"
fs.mount.lib2.uri = "file:/lib64"

fs.mount.lib3.type = "chroot"
fs.mount.lib3.path = "/usr/lib64"
fs.mount.lib3.uri = "file:/usr/lib64"

fs.mount.etc.type = "chroot"
fs.mount.etc.path = "/etc"
fs.mount.etc.uri = "file:/etc"

fs.mount.home.type = "chroot"
fs.mount.home.path = "/home/graphene"
fs.mount.home.uri = "file:/home/graphene"

fs.mount.tmp.type = "chroot"
fs.mount.tmp.path = "/tmp"
fs.mount.tmp.uri = "file:/tmp"

fs.mount.sysdev1.type = "chroot"
fs.mount.sysdev1.path = "/sys/devices"
fs.mount.sysdev1.uri = "file:/sys/devices"


loader.insecure__use_cmdline_argv = 1

# All trusted files and the user defined manifest specifications should be after this line
sgx.allow_file_creation = 1
sgx.enclave_size = "4G"
sgx.thread_num = 8

sgx.trusted_children.clscpu = "file:/home/graphene/lscpu.sig"

# Name Service Switch (NSS) files (Glibc reads these files)
sgx.allowed_files.nsswitch = "file:/etc/nsswitch.conf"
sgx.allowed_files.ethers = "file:/etc/ethers"
sgx.allowed_files.hosts = "file:/etc/hosts"
sgx.allowed_files.group = "file:/etc/group"
sgx.allowed_files.passwd = "file:/etc/passwd"

sgx.trusted_files.ld = "file:/usr/libexec/graphene/ld-linux-x86-64.so.2"
sgx.trusted_files.libc = "file:/usr/libexec/graphene/libc.so.6"
sgx.trusted_files.libm = "file:/usr/libexec/graphene/libm.so.6"
sgx.trusted_files.libdl = "file:/usr/libexec/graphene/libdl.so.2"
sgx.trusted_files.librt = "file:/usr/libexec/graphene/librt.so.1"
sgx.trusted_files.libpthread = "file:/usr/libexec/graphene/libpthread.so.0"
sgx.trusted_files.libutil = "file:/usr/libexec/graphene/libutil.so.1"

# Name Service Switch (NSS) libraries (Glibc dependencies)
sgx.trusted_files.libnsscompat = "file:/lib64/libnss_compat.so.2"
sgx.trusted_files.libnssfiles = "file:/lib64/libnss_files.so.2"
sgx.trusted_files.libnsl = "file:/lib64/libnsl.so.2"

sgx.trusted_files.libcrypto = "file:/lib64/libcrypto.so.1.1"
sgx.allowed_files.libz = "file:/lib64/libz.so.1"

sgx.trusted_files.kernel_maxx_ = "file:/sys/devices/system/cpu/kernel_max"
sgx.trusted_files.usr_share_locale = "file:/usr/share/locale/locale.alias"
sgx.trusted_files.usr_lib_locale_lc_ctype = "file:/usr/lib/locale/C.utf8/LC_CTYPE"
sgx.trusted_files.ls_cache = "file:/etc/ld.so.cache"
sgx.trusted_files.localtime = "file:/etc/localtime"


# Python
sgx.trusted_files.libpython3 = "file:/lib64/libpython3.6m.so.1.0"
sgx.allowed_files.python3    = "file:/usr/lib64/python3.6"
sgx.allowed_files.test_lscpu = "file:/home/graphene/test_lscpu.py"

sgx.allowed_files.cpu_possible = "file:/sys/devices/system/cpu/possible"
sgx.allowed_files.lscpu_ = "file:lscpu"
sgx.allowed_files.kernel_max_ = "file:/sys/devices/system/cpu/kernel_max"

```

**Comment by mhpanah** [comment] 2020-11-30 19:00
@dimakuv The graphene version that I'm using does not have #1975.  Let me update the graphene to see if that resolves this issue.

**Comment by dimakuv** [comment] 2020-11-30 19:12
@mhpanah Why do you have these lines in your lscpu manifest?

```
#sgx_allowed_files.kernel_max = "file:/sys/devices/system/cpu/kernel_max"
sgx.allowed_files.lscpu_ = "file:lscpu"
```

Why is the first (correct) line commented out? And what does the second line mean (did you try copy-pasting the file to your local directory)?

**Comment by dimakuv** [comment] 2020-11-30 19:16
Actually I think that the *real* chain of created processes is this: `python -> bash -> lscpu`. So because you don't have the `bash` manifest and trusted_child, you never get to the `lscpu` process...

You can check what the native version of your application does by doing `strace -ff` on it and searching for `clone/fork/execve` system calls. This will allow you to understand how processes are actually created under the hood in your application.

Next, you can set `loader.debug_type = "inline"` in both your manifests and analyze the resulting Graphene logs. Graphene probably silently fails on some `execve` system call, but it manifests in this `file is not trusted...` error in the end.

**Comment by mhpanah** [comment] 2020-11-30 19:19
@dimakuv  I wasn't sure if I needed both trusted_files and allowed_files.  At some point I had both and then I tried to experiment with just trused_files.  That's why I commented that line out.  

For lscpu, I created symbolink link. `ln -s /bin/lscpu /home/graphene`, to see if that would make a difference.

**Comment by svenkata9** [comment] 2021-01-12 11:37
@mhpanah Are you able to run lscpu now after the manifest update? I am trying to run and encountering an illegal instruction (and discussing with @dimakuv as well).

**Comment by dimakuv** [comment] 2021-01-12 12:12
Yes, we did `objdump -D /usr/bin/lscpu | grep "54f3:"` and found this:
```
 54f3:       ed                      in     (%dx),%eax 
```

So, lscpu tries to issue an `in` x86 instruction which is prohibited under Intel SGX (see https://c9x.me/x86/html/file_module_x86_id_139.html and https://software.intel.com/content/www/us/en/develop/documentation/sgx-developer-guide/top/processor-features/illegal-instructions-within-an-enclave.html). And Graphene doesn't emulate this instruction (indeed, it's unclear if this is even possible or reasonable from a security perspective).

**Comment by mkow** [comment] 2021-01-12 12:55
@dimakuv wait... this is a privileged instruction, I'm quite sure `lscpu` doesn't use it and you just disassembled some data ;)

**Comment by dimakuv** [comment] 2021-01-12 13:59
@mkow Why do you think it's privileged? It can be executed in user-mode from what I see.

You can also check that it is used in lscpu by `objdump -D /usr/bin/lscpu`. Yes, in a couple of places it is just random garbage but there is one place which is clearly a code path where this instruction is used.

And I'm pretty sure we hit it in lscpu under Graphene-SGX. It's another question of course, why would anyone want to run lscpu under Graphene...

**Comment by mkow** [comment] 2021-01-12 14:31
> Why do you think it's privileged?

Because the manual says so (but it's actually a bit more complicated, it's privileged in terms of `RFLAGS.IOPL` + `RFLAGS.CPL`, not just `RFLAGS.CPL` only, like with normal privileged instructions).

On Linux, there exists _the most ugly and hacky syscall_, ioperm, which asks kernel to enable I/O port access in usermode (I think this was made for 16-bit emulators?), but `lscpu` on my system is not using it. It also (obviously) requires root privileges and I think it was dropped from x64 Linux, but I'm not sure.

> You can also check that it is used in lscpu by objdump -D /usr/bin/lscpu. Yes, in a couple of places it is just random garbage but there is one place which is clearly a code path where this instruction is used.

Yes, I only found that one place, and it looks like used exactly for triggering an exception :)

**Comment by dimakuv** [comment] 2021-01-12 14:48
> Yes, I only found that one place, and it looks like used exactly for triggering an exception :)

Ah, ok. So we actually triggered a legit exception under Graphene then :)

**Comment by mkow** [comment] 2021-01-12 15:43
Let me take a look into this.

**Comment by mkow** [comment] 2021-01-13 01:04
`lscpu` works for me, or at least doesn't crash. It prints `lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory` and exits (which is expected until we merge #1975).
I tested this on #2050, as asked above by @svenkata9.

So... @svenkata9: How can I reproduce the issue? How exactly are you running it?

**Comment by svenkata9** [comment] 2021-01-13 01:52
@mkow  lscpu accesses many such files. Please allow all the file access. You should then be able to see the issue.

**Comment by mkow** [comment] 2021-01-13 02:26
What do you mean by "allow"? These files just doesn't exist under Graphene currently, we'll have them once we merge #1975.

**Comment by svenkata9** [comment] 2021-01-13 04:38
I did this: **sgx.file_check_policy = "allow_all_but_log"**

And then added these to fs.mount:
/sys/devices

**Comment by mkow** [comment] 2021-01-13 12:26
Mounting special filesystems from host is a bad idea and probably doesn't work as expected, this "chroot" mount is intended to be used to mount regular files and directories, also, /sys on the host has wrong contents (from the host, not from the emulated Linux inside Graphene).

Please try rebasing #1975 on top of current master and using it, it has a proper emulation of `/sys/devices/system/cpu`.

**Comment by mkow** [comment] 2021-02-09 02:16
@vijaydhanraj This seems to be caused by a bug in the sysfs code:
```
> cat /sys/devices/system/cpu/possible
cat: can't open '/sys/devices/system/cpu/possible': No such file or directory
```

From what I see it's caused by this function: https://github.com/oscarlab/graphene/blob/79742f90293992394084e7460a039173579701f9/LibOS/shim/src/fs/sys/cpu_info.c#L16
It fails to extract the number from the path for `possible` entry and returns `-ENOENT`: https://github.com/oscarlab/graphene/blob/79742f90293992394084e7460a039173579701f9/LibOS/shim/src/fs/sys/cpu_info.c#L24-L26
This `cpu_info_open` IMO oversimplified the real directory structure there, I'm afraid we'd need to create proper  `pseudo_dir` structs and handlers for each of the special directories there.

Could you take a look at this?

**Comment by vijaydhanraj** [comment] 2021-02-09 03:30
sure, let me take a look.

**Comment by dimakuv** [comment] 2021-02-09 09:39
Yes, this is a fail :)

On the one hand, we have a no-numbers-path `/sys/devices/system/cpu/possible`. On the other hand, we try `extract_first_num_from_string()` which obviously fails.

I suggest to:
- if there is only one (`possible`) file that is located under such a no-numbers-path, simply move its handling before `extract_first_num_from_string()` (i.e., special-case it in the same function),
- if there is more than just this one file that are located under such a path, then extract their handling in a separate function and make the `/sys/` directory hierarchy contain more levels of structs, as Michal suggests.

**Comment by vijaydhanraj** [comment] 2021-02-09 20:29
Please try with the new PR https://github.com/oscarlab/graphene/pull/2153. We do have appropriate `pseudo_dir` struct but we end up using the same `fs_ops` function for both the numeric and non-numeric paths. But since these were just 2 cases (`online` and `possible`), have special-cased it to reduce code duplication.

**Comment by mkow** [comment] 2021-02-15 01:51
I tested #2153 and now `lscpu` fails on a NULL-deref right after trying to probe PCI devices information from sysfs. I guess it just doesn't handle the lack of full sysfs information well, but I didn't analyze `lscpu` source to be really sure.

Btw. A note to anyone who'd try to debug the issue: the first SIGSEGV happening inside is legit and should be passed to `lscpu`, it's just trying to detect hypervisors via `in` instruction with magic constants.

**Comment by mkow** [comment] 2021-08-31 14:53
Ok, it seems that this is just `lscpu` assuming that everything in `/sys` is available and having no error checking. We don't plan to implement PCI devices information in sysfs, so I'm closing this issue.

**Closed by mkow** 2021-08-31 14:53 UTC
Labels: bug, P: 2
