### ISSUE TITLE
clone03 is flaky

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#529] opened 2019-03-15 23:53 UTC
`clone03,1` from LTP fails from time to time.

Bash script for repro:
```Bash
for i in `seq 1 3000`; do
    echo "[$i]"
    ../../../../pal_loader clone03 || break
done
```

Example output, after running in `LibOS/shim/test/apps/ltp/opt/ltp/testcases/bin`:
```
[...]
[1366]
WARNING: no physical memory support, process creation may be slow.
clone03     1  TBROK  :  clone03.c:93: read from pipe failed: errno=EINTR(4): Interrupted system call
clone03     2  TBROK  :  clone03.c:93: Remaining cases broken
```

**Comment by dimakuv** [comment] 2019-07-12 23:47
The issue is that the parent process reads on the pipe:
```c
        /* Read pid from read end */
        if ((read(pfd[0], buff, sizeof(buff))) == -1)
            tst_brkm(TBROK | TERRNO, cleanup,
                 "read from pipe failed");
```
simultaneously with the child process writing to this pipe and then exiting immediately:
```c
    /* Write pid string to pipe */
    if ((write(pfd[1], pid, sizeof(pid))) == -1)
        perror("write to pipe failed");

    /* Close write end of pipe from child */
    if ((close(pfd[1])) == -1)
        perror("close(pfd[1]) failed");

    exit(1);
```

Notice that child just exits. Linux is smart enough to keep the pipe alive until the parent closes this pipe/dies. Unfortunately, Graphene emulation of pipes kills the underlying host-OS abstraction (I didn't dig too deep so not sure where exactly this happens), and when the child dies, its associated pipe closes in Graphene. So the parent's attempt to `read()` fails.

Interestingly, because Graphene emulates parent-child processes as a distributed system, it may be impossible to correctly pass this test (there is no "central entity" to cache data sent on the closing pipe).

**Closed** 2019-07-28 00:19 UTC
Labels: bug
