### ISSUE TITLE
[UX] `make` in libOS failed if `make SGX=1` is done in Pal

### ISSUE THREAD

**Issue by chiache** [oscarlab/graphene#782] opened 2019-06-22 09:32 UTC
If you run `make SGX=1` in the `Pal/src` directory first, and then run `make` in `LibOS/shim/src`, the following error appears:

```
make[1]: Leaving directory '/home/chiache/Workspace/graphene_project/graphene/Pal/lib'
make: *** No rule to make target '/home/chiache/Workspace/graphene_project/graphene/LibOS/shim/src/../../../Runtime/libpal-Linux.so', needed by 'libsysdb.so'.  Stop.
```

This issue happens when the users do not do a clean build and instead incrementally build each source directory (which is the way suggested by our Wiki). IMHO we should support both clean build and incremental build, and the `make` command in `LibOS/shim/src` should not depend on whether `make` or `make SGX=1` is run in `Pal/src`.

**Comment by yamahata** [comment] 2019-07-09 19:41
The root cause is that multiple configurations are mixed.
i.e. with SGX=1 or without SGX.
In LibOS, with SGX=1, libos is linked to pal-Linux-SGX. without SGX libos is linked to pal-Linux.
something is wrong.
One solution is to introduce compile-time config and allow the configuration to build.
If we'd like to have multiple configs from single source, out-of-source-tree build should be supported.

**Comment by mkow** [comment] 2020-07-31 00:04
Just tested and this is not the case anymore. We support building SGX and non-SGX PALs at the same time since long ago. Closing.

**Closed by mkow** 2020-07-31 00:04 UTC
