### ISSUE TITLE
graphene-sgx does not compile

### ISSUE THREAD

**Issue by shmeni** [oscarlab/graphene#22] opened 2016-12-05 14:42 UTC
Hey,
I got the following problem trying to compile graphene right now:

(On Ubuntu 14.04, able to run native SGX apps)
Cloned a fresh copy of graphene, use latest driver, sdk & psw.
Tried to compile with SGX=1 and got an error while signing enclave:

  File "/home/user/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 211, in resolve_uri
raise Exception('Cannot resolve ' + orig_uri + ' or the file does not exist.')
Exception: Cannot resolve /src/libsysdb.so or the file does not exist.

**Comment by chiache** [comment] 2016-12-05 18:22
Which application are you testing? Is it a manifest you created on your own?

**Comment by shmeni** [comment] 2016-12-06 09:20
It fails when compiling graphene from the root dir.

It fails when it gets to the path: LibOS/shim/test/native and tries to sign the file: static.manifest.sgx

**Comment by adombeck** [comment] 2016-12-06 12:38
> File "/home/user/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 211, in resolve_uri
> raise Exception('Cannot resolve ' + orig_uri + ' or the file does not exist.')
> Exception: Cannot resolve /src/libsysdb.so or the file does not exist.

This doesn't seem right. This exception is raised in line 203, not in line 211.

**Comment by shmeni** [comment] 2016-12-06 12:41
Right my bad, I tried to create a temp fix and it screwed the line numbering. Line 203 is right.

**Comment by adombeck** [comment] 2016-12-06 12:59
I guess the first line in `graphene/LibOS/shim/test/native/static.manifest.sgx` is `loader.preload = file:/src/libsysdb.so`, right?

**Comment by shmeni** [comment] 2016-12-06 13:01
Yep: "loader.preload = file:/../../src/libsysdb.so"

**Comment by adombeck** [comment] 2016-12-06 13:07
The leading slash shouldn't be there. I'm not a developer of this project, but I had a similar bug yesterday, which was caused by the use of `realpath` inside a makefile, which is not installed in Ubuntu 14.04. This was fixed yesterday, see https://github.com/oscarlab/graphene/pull/21. Maybe try pulling the latest commits and building again.

**Comment by chiache** [comment] 2017-01-14 14:41
This problem shall be fixed in the latest version.

**Closed by chiache** 2017-01-14 14:41 UTC
