### ISSUE TITLE
[PAL/SHIM] Are sockets closed such that the OS knows about it? 

### ISSUE THREAD

**Issue by martinschmatz** [oscarlab/graphene#765] opened 2019-06-19 13:39 UTC
Observation: I prepare a fd via socket, bind & listen calls. When then getting a socket via accept4 call for that listener, and at some point later later stop listening and closing that very same socket, I get (as expected) the following debug output: 
[     1] ---- shim_accept4(8,0x0,0x0,526336) ... accept4
[     1] ---- return from shim_accept4(...) = **12**
[.....] many more lines
[     1] ---- shim_epoll_ctl(9,2,**12**,0x0) = 0
[     1] ---- shim_close(**12**) = 0
So far, so good. 

However, I see an ever increasing number of open file descriptors when checking with sudo lsof -a -p [myprocessnumber], generating an output like this: 

[...many more of the same...]
pal-Linux 24426 root  279u  sock                0,9      0t0 31741611 protocol: TCP
pal-Linux 24426 root  280u  sock                0,9      0t0 31741613 protocol: TCP
pal-Linux 24426 root  281u  sock                0,9      0t0 31741615 protocol: TCP
pal-Linux 24426 root  282u  sock                0,9      0t0 31741617 protocol: TCP
pal-Linux 24426 root  283u  sock                0,9      0t0 31741619 protocol: TCP
pal-Linux 24426 root  284u  sock                0,9      0t0 31741621 protocol: TCP
[...many more of the same....]

This continues until the limit of allowed file descriptors as defined by the OS is reached - at which point accept4 returns error -13 (EACCESS???) and my app crashes. 
Doubling the max number of allowed fds in the OS via ulimit -n doubles the number of cycles in my app before it crashes. 

The app runs like a charm outside of Graphene. 

Question: Are sockets generated with accept4 really closed in a manner such that the OS book-keeping is aware of it? 

I guess the relevant closing is ultimately done in _DkObjectClose in db_object.c, right? If so, there should an 'ops->close' operation be defined for and attached to the related objectHandle. So far, I wasn't able to find where this 'ops->close' procedure is assigned to the objectHandle for socket-like file descriptors as objectHandles. 

I'd appreciate if a Graphene-expert could look into that and double check that the OS book-keeping is aware of closed sockets. Thanks!

**Comment by martinschmatz** [comment] 2019-06-19 16:21
Addendum to the above: 
The issue occurs when I connect to the same IP:PORT inside Graphene in quick sequence from the same source outside Graphene (SO_REUSEADDR is set to 1). Same behavior irrespective of whether the the source is on the same server on a remote server. 
Can it be that accept4 inside Graphene provides the app the same fd when using accept4 and close for the listening socket over and over again from the same source (that's at least what I observe in the debug messages - and actually also would expect), but that Graphene requests a fresh fd from the OS each time?

**Comment by dimakuv** [comment] 2019-06-19 21:25
I cannot reproduce whatever error you hit. I modified slightly the example in `LibOS/shim/test/native/tcp.c` but still don't see any issues.

The general call sequence for syscall `close(tcp-socket)` is like this: `shim_do_close -> close_handle -> put_handle -> [...crossing LibOS->PAL border...] -> DkObjectClose -> _DkObjectClose -> socket_close`. Note that the last function is found under `Pal/src/host/Linux/db_sockets.c: socket_close()` (from your logs I assume you attest on regular Linux PAL, without SGX).

If you look at `Pal/src/host/Linux/db_sockets.c`, you will find that it defines:
```c
struct handle_ops tcp_ops = {
        ...
        .close          = &socket_close,
        ...
};
```

This object `tcp_ops` is used in `Pal/src/db_streams.c`. Now this is where it gets a little crazy.

0. LibOS's task on emulating `socket()/bind()/connect()/close()/...` is to get a socket handle or `PAL_HANDLE`. Below I describe how exactly this happens.
1. LibOS's emulation of `bind()` and `connect()` (which are `shim_do_bind()` and `shim_do_connect()`) calls PAL's `DkStreamOpen(uri-string)`.
2. PAL's `DkStreamOpen()` calls `_DkStreamOpen()`.
3. `_DkStreamOpen()` calls `parse_stream_uri(uri-string, ..., &ops)`.
4. `parse_stream_uri()` looks into `uri-string`, figures out that it has to do with a TCP socket, and populates `ops = &tcp_ops`.
5. Next `_DkStreamOpen()` calls `ops->open(&handle, ...)`.
6. This call translates to `tcp_ops->open()` which is `Pal/src/host/Linux: tcp_open()`.
7. `tcp_open()` calls `tcp_listen(&handle, ...)`.
8. `tcp_listen()` finally does some real stuff! It issues actual host-OS syscalls `socket()`, `bind()`, `listen()` and most importantly for us, it does `*handle = socket_create_handle()`.
9. So now this `PAL_HANDLE handle` is finally initialized and is propagated back to LibOS.
10. `shim_do_bind()` and `shim_do_connect()` memorize this `PAL_HANDLE` using this line: `hdl->pal_handle = pal_hdl`.

So this is how LibOS ends up memorizing `PAL_HANDLE pal_hdl` object inside its own `shim_handle hdl` object. On `shim_do_close()`, this PAL_HANDLE will be propagated all the way to `Pal/src/host/Linux/db_sockets.c: socket_close(PAL_HANDLE handle)`.

**Comment by dimakuv** [comment] 2019-06-19 21:33
Ok, this was just an explanation of how LibOS learns PAL's handle and how PAL uses this handle to actually do host-OS syscalls.

This doesn't explain why you see your bug. When I run my TCP example, I see how the handle is correctly closed in host OS (I use `strace -ff ./pal_loader tcp` and `GDB=1 ./pal_loader tcp` for debugging).

One idea is that you (well, Graphene under your particular workload) have a dangling reference to `PAL_HANDLE`. Note how `put_handle()` is implemented in `LibOS/shim/src/bookkeep/shim_handle.c`:
```c
void put_handle (struct shim_handle * hdl) {
    int ref_count = REF_DEC(hdl->ref_count);
    if (!ref_count) {
        if (hdl->fs && hdl->fs->fs_ops && hdl->fs->fs_ops->hput)
            hdl->fs->fs_ops->hput(hdl);

        if (hdl->pal_handle) {
            DkObjectClose(hdl->pal_handle);
            hdl->pal_handle = NULL;
        }
    ...
    }
```

What this code means is that `DkObjectClose()` is only called when there are no more references on the LibOS handle for this TCP socket. I can imagine that Graphene has a subtle bug somewhere deep in TCP handling mechanisms which forgets to release the reference.

So you can either (1) send a concrete program which exhibits your bug and I debug it, or (2) run GDB/debug in your head. Either way, seems like a legit bug.

**Comment by martinschmatz** [comment] 2019-06-20 05:41
Many thanks for the detailed explanations! I'll digest those - will help me to better understand the subtleties of Graphene...;-)) 

Here's what I've changed in the tpc.c example to be able to replicate the observation/issue: 
1) Explicitly ask for TCP protocol (using IPPROTO_TCP instead of using the dummy '0'); not sure that's needed to replicate the observation/issue, but that's how I do it in my app):
`    if ((create_socket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)) > 0)`
2)  Keep the server active by using a `while(1)` loop around the key section (obviously **not** closing the bound/listening 'parent' socket `create_socket` by commenting out that line): 

```
    while (1) {
        new_socket = accept(create_socket, (struct sockaddr *) &address,
                            &addrlen);

        if (new_socket < 0) {
            perror("accept");
            close(create_socket);
            exit(-1);
        }

        //close(create_socket);

        if (do_fork) {
            if (fork() > 0) {
                close(new_socket);
                wait(NULL);
                return 0;
            }
        }

        char buff[18] = {'\0'};
        if (inet_ntop(AF_INET, &address.sin_addr, buff, 18) <= 0)
            perror("address conversion");

        printf("The client %s is connected...\n", buff);

        if ((fd = open(fname, O_RDONLY, 0)) < 0) {
            perror("file open failed");
            close(new_socket);
            close(create_socket);
            exit(-1);
        }

        while ((conn = read(fd, buffer, bufsize)) > 0)
            sendto(new_socket, buffer, conn, 0, 0, 0);

        printf("Request completed\n");

        close(new_socket);
        if (do_fork)
            exit(0);

    }

```
The rest of the tcp.c example is left unchanged.
I'd say the above is a reasonable simplification of what my app does - minus the event based operation, minus the multi-threading, minus [..., ..., ....] of my app. 

I start the tcp.c example server this way (after a 'make' in the example directory, obviously): 
1) sudo /relevant_path/pal-sgx-sign -libpal /relevant_path/libpal-Linux-SGX.so -key /relevant_path/enclave-key.pem -output tcp.manifest.sgx -manifest tcp.manifest
2) sudo /relevant_path/pal-sgx-get-token -output tcp.token -sig tcp.sig
3) sudo /relevant_path/pal-Linux-SGX ./tcp server

I then repeatedly execute (in a different console on the same server) ./tcp client

When doing this, I see an ever growing number of file handles when checking the list of file handles via sudo lsof -a -p [process_number] ==> One additional entry in that list for each execution of ./tcp client

Can you perhaps replicate this?

**Comment by martinschmatz** [comment] 2019-06-20 06:11
UUUUppps: I forgot to close the file that is sent in my modified tcp.c example - which is why I see increasing number of file handles. 
Sorry!
When closing the file by adding `close(fd);` after `printf("Request completed\n");`, I also can't replicate the observation/issue with the (modified) tcp.c example
==> Need to spend some more time to carve out a simplified version of my app to share.....coming back as soon as I have one....

**Comment by dimakuv** [comment] 2019-06-20 19:48
:) Yes, I believe your code is doing something corner-case-ish. In the worst case, is it open-sourced? I could also just clone it and follow your instructions to reproduce.

**Comment by martinschmatz** [comment] 2019-06-21 06:22
While the components of my code come from open source (OpenSSL, nghttp2, curl, h2o), the combination of those unfortunately is not open source (at least not yet). 
It might well be that something 'corner-case-ish' is hidden in the HTTP2 and tlsv1.3 parts, or in the event loop, or the asynchronous multi-threading.
I'm currently trying to establish a code example which shows the issue, while I'm at the same time re-examining my code to see if there could be a workaround - despite the fact that the code works just fine outside of Graphene.

**Comment by martinschmatz** [comment] 2019-06-21 19:14
What solved my problem was to add `put_handle(hdl);` in the `EPOLL_CTL_DEL` case statement of `LibOS/shim/src/sys/shim_epoll.c` (see below). 

Reasoning: In the `EPOLL_CTL_ADD` section of the case statement, there's a call to `get_fd_handle`, which increases the ref-count on the handle. Without decreasing this ref-count when the epoll is de-registered, the ref-count is ever increasing, never going back to zero, hence `DkObjectClose(hdl->pal_handle);` is never executed in `LibOS/shim/src/bookkeep/shim_handle.c` - and the number of file handles increases and increases until hitting the limit set by the OS. 

If you agree with that reasoning, I can issue a PR. 

```
        case EPOLL_CTL_DEL: {
            LISTP_FOR_EACH_ENTRY(epoll_fd, &epoll->fds, list)
                if (epoll_fd->fd == fd) {
                    struct shim_handle * hdl = epoll_fd->handle;

                    /* Unregister the epoll handle */
                    lock(&hdl->lock);
                    LISTP_DEL(epoll_fd, &hdl->epolls, back);
                    unlock(&hdl->lock);
                    put_handle(epoll_hdl);
                    put_handle(hdl);

                    debug("delete handle %p from epoll handle %p\n",
                          hdl, epoll);

                    LISTP_DEL(epoll_fd, &epoll->fds, list);
                    epoll->nfds--;
                    free(epoll_fd);
                    goto update;
                }

            ret = -ENOENT;
            goto out;
        }
```

**Comment by martinschmatz** [comment] 2019-06-21 19:16
Obviously that's in the following function:
```
int shim_do_epoll_ctl (int epfd, int op, int fd,
                       struct __kernel_epoll_event * event)
```

**Comment by dimakuv** [comment] 2019-06-21 20:27
Yes, this looks a legit bug and your fix looks correct. I would only move the puts after the debug:
```c
                    ...
                    unlock(&hdl->lock);

                    debug("delete handle %p from epoll handle %p\n",
                          hdl, epoll);

                    put_handle(epoll_hdl);
                    put_handle(hdl);

                    LISTP_DEL(epoll_fd, &epoll->fds, list);
                    ...
```

Please submit a PR.

**Closed** 2019-07-28 01:17 UTC
