### ISSUE TITLE
[LibOS/shim/test/apps/openvino] make fail

### ISSUE THREAD

**Issue by TomTanJun** [oscarlab/graphene#1205] opened 2019-12-06 03:13 UTC
Env: Ubuntu 18.04

After install the following prerequisite packages, compile failed

* Install CMake version >= 3.7.2 (on Ubuntu 16.04, this may require installing
  Cmake from a non-official APT repository like Kitware).

* Install libusb version >= 1.0.0.

* Install packages for Python3:
  `pip3 install pyyaml numpy networkx test-generator defusedxml protobuf>=3.6.1`

`make SGX=1`

```
[ 36%] Built target cpplint_all
make[3]: Entering directory '/root/graphene/LibOS/shim/test/apps/openvino/openvino/inference-engine/build
thirdparty/CMakeFiles/mkldnn.dir/build.make:4867: *** target pattern contains no '%'.  Stop.
make[3]: Leaving directory '/root/graphene/LibOS/shim/test/apps/openvino/openvino/inference-engine/build'
CMakeFiles/Makefile2:2245: recipe for target 'thirdparty/CMakeFiles/mkldnn.dir/all' failed
make[2]: *** [thirdparty/CMakeFiles/mkldnn.dir/all] Error 2
make[2]: Leaving directory '/root/graphene/LibOS/shim/test/apps/openvino/openvino/inference-engine/build'
Makefile:162: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/graphene/LibOS/shim/test/apps/openvino/openvino/inference-engine/build'
Makefile:63: recipe for target 'openvino/inference-engine/bin/intel64/Release/object_detection_sample_ssd' failed
make: *** [openvino/inference-engine/bin/intel64/Release/object_detection_sample_ssd] Error 2
```

**Comment by dimakuv** [comment] 2020-03-30 20:18
@TomTanJun I cannot reproduce this on my local machine. Is this still relevant?

**Comment by dimakuv** [comment] 2020-04-09 17:35
Could not reproduce this, closing.

**Closed by dimakuv** 2020-04-09 17:35 UTC
