### ISSUE TITLE
[LibOS/shim/test/native] pid_kill run fail

### ISSUE THREAD

**Issue by TomTanJun** [oscarlab/graphene#1158] opened 2019-11-21 06:31 UTC
```
#./pal_loader SGX pid_kill
...
** An unexpected AEX vector occurred inside PAL. Exiting the thread. ***
(vector = 0x2, type = 0x0 valid = 0, RIP = +0x0000b570)
rax: 0x80befa250 rcx: 0x00000040 rdx: 0x00000080 rbx: 0x00000000
rsp: 0x809733dd0 rbp: 0x7ffc3bdd1514 rsi: 0x7ffc3bdd1514 rd[     2] signal_logs[9]: head=28, tail=28
[     2] SIGUSR1 handled
i: 0x7ffc3bdd1514
r8 : 0x00000049 r9 : 0x80befa250 r10: 0x7ffc3bdd1514 r11: 0x7ffc3bdd1514
r12: 0x7ffc3bdd1514 r13: 0x00000000 r14: 0x00000049 r15: 0x80befa250
rflags: 0x00010206 rip: 0x80bcb8570
[     2] run signal handler 0x80baa9a1a (10, 0x80b79af70, 0x80b79aff8)
pausing for debug
[     2] walk_thread_list(callback=0x80b8366b3)
[     2] IPC send to 17986: IPC_PID_KILL(2, 1, 3, 10)
[     2] Sending ipc message to port 0x80b75a150 (handle 0x80befa0d0)
[     2] ---- shim_kill(3,SIGUSR1) = 0
```

**Comment by dimakuv** [comment] 2019-11-21 19:04
Strange, I do not observe this in the latest master. I ran it several times in debug and production builds of Graphene, with and without inline logs. Could you verify that you still see this error on the latest master version?

**Comment by mkow** [comment] 2020-07-31 12:27
I also can't reproduce the issue, closing.
btw. There's another issue with this test though: it hangs both on SGX and natively, so it's broken like most of the things inside LibOS/shim/test/native. Everything in this directory should be reworked, but it's unrelated to this particular issue.

**Closed by mkow** 2020-07-31 12:27 UTC
