### ISSUE TITLE
Issue while running helloworld program

### ISSUE THREAD

**Issue by Nidhimidha** [oscarlab/graphene#202] opened 2018-04-13 23:33 UTC
I am using Linux 16.04 and I am trying to follow steps mentioned on https://github.com/oscarlab/graphene/wiki/SGX-Quick-Start.

I have followed all the prerequisites such as installing linux-sgx and linux-sgx-driver. When i was asked to write down the path for sgx-driver in 3rd step, I gave below information:

Enter the Intel SGX driver directory: home/yashshvi/Downloads/linux-sgx-driver-sgx2
Enter the driver version (default: 1.9): 2.0

Though I am getting an issue when trying to run fifth step, i.e., "Run a helloworld program".
Below are the results after running the commands. What could possibly be issue since I had been following everything step by step? Any help would be really appreciated.

`yashshvi@yashshvi-Lenovo-YOGA-710-15IKB:~/Downloads/graphene$ cd LibOS/shim/test/native yashshvi@yashshvi-Lenovo-YOGA-710-15IKB:~/Downloads/graphene/LibOS/shim/test/native$ make SGX=1 make: *** No rule to make target 'static.manifest.sgx', needed by 'all'. Stop. yashshvi@yashshvi-Lenovo-YOGA-710-15IKB:~/Downloads/graphene/LibOS/shim/test/native$ make SGX_RUN=1 make: *** No rule to make target 'static.token', needed by 'all'. Stop. yashshvi@yashshvi-Lenovo-YOGA-710-15IKB:~/Downloads/graphene/LibOS/shim/test/native$ ./pal_loader SGX helloworld or SGX=1 ./pal_loader helloworld /home/yashshvi/Downloads/graphene/Runtime/pal-Linux-SGX is not built, or security mode is not supported`

**Comment by donporter** [comment] 2018-06-28 18:29
@Nidhimidha were you able to resolve this issue?

**Comment by dimakuv** [comment] 2018-11-21 18:18
@kausk , can you run `gcc -dumpmachine` on your machine:
```
$ gcc -dumpmachine
x86_64-linux-gnu
```

What is the returned value? It should be `x86_64-linux-gnu`.

The suspicious like in your output is this:
`gcc -Wall -O2 -std=gnu99 -fgnu89-inline -fno-builtin -nostdlib -I../include/pal -I../lib    HelloWorld.c   -o HelloWorld`

There are no libraries mentioned, that's why you have "undefined reference" errors. If you look at `Pal/test/Makefile`, line 40, you will see `$(graphene_lib) $(pal_lib)` as dependencies. They are missing in your gcc invocation. Most probably, because your machine is not `x86_64-linux-gnu`.

**Comment by rainfld** [comment] 2018-12-24 05:36
Hi, @Vampsj This is very likely because recent updates has broken the dependencies in native compilation. We have a fix in https://github.com/oscarlab/graphene/pull/391 not merged. Please give a try with this. It should resolve your issue.

**Comment by Vampsj** [comment] 2018-12-24 05:42
@rainfld Yes, it worked! Thank you very much!

**Comment by mkow** [comment] 2019-02-15 12:25
As #391 was merged recently, I'm closing this issue.

**Closed by mkow** 2019-02-15 12:25 UTC
Labels: bug, need update

**Comment by Nithinccu** [comment] 2019-04-08 16:01
Having the issue as below, and this is what I'm getting when I run your instructions:

sgx@SGX:~/Desktop/graphene$ make SGX=1
make -C Pal all
make[1]: Entering directory '/home/sgx/Desktop/graphene/Pal'
for d in src test regression; \
do \
	make -C $d all || exit ; \
done
make[2]: Entering directory '/home/sgx/Desktop/graphene/Pal/src'
make -C ../lib target=/home/sgx/Desktop/graphene/Pal/src/host/Linux-SGX/.lib/
make[3]: Entering directory '/home/sgx/Desktop/graphene/Pal/lib'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/sgx/Desktop/graphene/Pal/lib'
make[3]: Entering directory '/home/sgx/Desktop/graphene/Pal/src/host/Linux-SGX'
[ host/Linux-SGX/sgx_framework.o ]
sgx_framework.c: In function ‘init_enclave’:
sgx_framework.c:360:14: error: ‘SGX_INVALID_LICENSE’ undeclared (first use in this function); did you mean ‘SGX_INVALID_KEYNAME’?
         case SGX_INVALID_LICENSE:
              ^~~~~~~~~~~~~~~~~~~
              SGX_INVALID_KEYNAME
sgx_framework.c:360:14: note: each undeclared identifier is reported only once for each function it appears in
Makefile:61: recipe for target 'sgx_framework.o' failed
make[3]: *** [sgx_framework.o] Error 1
make[3]: Leaving directory '/home/sgx/Desktop/graphene/Pal/src/host/Linux-SGX'
Makefile:96: recipe for target 'host/Linux-SGX/libpal-Linux-SGX.a' failed
make[2]: *** [host/Linux-SGX/libpal-Linux-SGX.a] Error 2
make[2]: Leaving directory '/home/sgx/Desktop/graphene/Pal/src'
Makefile:19: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/sgx/Desktop/graphene/Pal'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dimakuv** [comment] 2019-04-08 18:40
You are experiencing one of these issues (most probably you incorrectly specified your SGX driver):
* https://github.com/oscarlab/graphene/issues/419
* https://github.com/oscarlab/graphene/issues/238

Please try the solutions in these issues and report back in case of troubles.

**Comment by Nithinccu** [comment] 2019-05-14 17:21
Having the issue as below, and this is what I'm getting when I run your instructions:

Successfully installed SGX-Driver, SGX-SDK, SGX-PSW,  

1) Simulation Mode (It's working fine)
work@work:~/Desktop/Project-work/linux-sgx/linux/installer/bin/sgxsdk/SampleCode/LocalAttestation$ make SGX_MODE=SIM
make[1]: Entering directory '/home/work/Desktop/Project-work/linux-sgx/linux/installer/bin/sgxsdk/SampleCode/LocalAttestation'
GEN  =>  LocalAttestationCode/LocalAttestationCode_t.h
CC   <=  LocalAttestationCode/LocalAttestationCode_t.c
CC   <= LocalAttestationCode/EnclaveMessageExchange.cpp
GEN  =>  libLocalAttestation_Trusted.a
CC   <=  Untrusted_LocalAttestation/UntrustedEnclaveMessageExchange.cpp
GEN  =>  libLocalAttestation_unTrusted.a
GEN  =>  Enclave1/Enclave1_t.h
CC   <=  Enclave1/Enclave1_t.c
CXX  <=  Enclave1/Utility_E1.cpp
CXX  <=  Enclave1/Enclave1.cpp
LINK =>  Enclave1.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 1953792B.
Succeed.
SIGN =>  libenclave1.so
GEN  =>  Enclave2/Enclave2_t.h
CC   <=  Enclave2/Enclave2_t.c
CXX  <=  Enclave2/Enclave2.cpp
CXX  <=  Enclave2/Utility_E2.cpp
LINK =>  Enclave2.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 1953792B.
Succeed.
SIGN =>  libenclave2.so
GEN  =>  Enclave3/Enclave3_t.h
CC   <=  Enclave3/Enclave3_t.c
CXX  <=  Enclave3/Enclave3.cpp
CXX  <=  Enclave3/Utility_E3.cpp
LINK =>  Enclave3.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 1953792B.
Succeed.
SIGN =>  libenclave3.so
GEN  =>  Enclave1/Enclave1_u.h
CC   <=  Enclave1/Enclave1_u.c
GEN  =>  Enclave2/Enclave2_u.h
CC   <=  Enclave2/Enclave2_u.c
GEN  =>  Enclave3/Enclave3_u.h
CC   <=  Enclave3/Enclave3_u.c
CXX  <=  App/App.cpp
LINK =>  app
The project has been built in debug simulation mode.
make[1]: Leaving directory '/home/work/Desktop/Project-work/linux-sgx/linux/installer/bin/sgxsdk/SampleCode/LocalAttestation'

work@work:~/Desktop/Project-work/linux-sgx/linux/installer/bin/sgxsdk/SampleCode/LocalAttestation$ ./app
Available Enclaves
Enclave1 - EnclaveID aca00000002
Enclave2 - EnclaveID aca00000003
Enclave3 - EnclaveID aca00000004

Secure Channel Establishment between Source (E1) and Destination (E2) Enclaves successful !!!
Enclave to Enclave Call between Source (E1) and Destination (E2) Enclaves successful !!!
Message Exchange between Source (E1) and Destination (E2) Enclaves successful !!!
Secure Channel Establishment between Source (E1) and Destination (E3) Enclaves successful !!!
Enclave to Enclave Call between Source (E1) and Destination (E3) Enclaves successful !!!
Message Exchange between Source (E1) and Destination (E3) Enclaves successful !!!
Secure Channel Establishment between Source (E2) and Destination (E3) Enclaves successful !!!
Enclave to Enclave Call between Source (E2) and Destination (E3) Enclaves successful !!!
Message Exchange between Source (E2) and Destination (E3) Enclaves successful !!!
Secure Channel Establishment between Source (E3) and Destination (E1) Enclaves successful !!!
Enclave to Enclave Call between Source (E3) and Destination (E1) Enclaves successful !!!
Message Exchange between Source (E3) and Destination (E1) Enclaves successful !!!
Close Session between Source (E1) and Destination (E2) Enclaves successful !!!
Close Session between Source (E1) and Destination (E3) Enclaves successful !!!
Close Session between Source (E2) and Destination (E3) Enclaves successful !!!
Close Session between Source (E3) and Destination (E1) Enclaves successful !!!
Hit a key....


2) Hardware Mode (It's showing the error)

work@work:~/Desktop/Project-work/linux-sgx/linux/installer/bin/sgxsdk/SampleCode/LocalAttestation$ make 
make[1]: Entering directory '/home/work/Desktop/Project-work/linux-sgx/linux/installer/bin/sgxsdk/SampleCode/LocalAttestation'
GEN  =>  LocalAttestationCode/LocalAttestationCode_t.h
CC   <=  LocalAttestationCode/LocalAttestationCode_t.c
CC   <= LocalAttestationCode/EnclaveMessageExchange.cpp
GEN  =>  libLocalAttestation_Trusted.a
CC   <=  Untrusted_LocalAttestation/UntrustedEnclaveMessageExchange.cpp
GEN  =>  libLocalAttestation_unTrusted.a
GEN  =>  Enclave1/Enclave1_t.h
CC   <=  Enclave1/Enclave1_t.c
CXX  <=  Enclave1/Utility_E1.cpp
CXX  <=  Enclave1/Enclave1.cpp
LINK =>  Enclave1.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 1957888B.
Succeed.
SIGN =>  libenclave1.so
GEN  =>  Enclave2/Enclave2_t.h
CC   <=  Enclave2/Enclave2_t.c
CXX  <=  Enclave2/Enclave2.cpp
CXX  <=  Enclave2/Utility_E2.cpp
LINK =>  Enclave2.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 1957888B.
Succeed.
SIGN =>  libenclave2.so
GEN  =>  Enclave3/Enclave3_t.h
CC   <=  Enclave3/Enclave3_t.c
CXX  <=  Enclave3/Enclave3.cpp
CXX  <=  Enclave3/Utility_E3.cpp
LINK =>  Enclave3.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 1957888B.
Succeed.
SIGN =>  libenclave3.so
GEN  =>  Enclave1/Enclave1_u.h
CC   <=  Enclave1/Enclave1_u.c
GEN  =>  Enclave2/Enclave2_u.h
CC   <=  Enclave2/Enclave2_u.c
GEN  =>  Enclave3/Enclave3_u.h
CC   <=  Enclave3/Enclave3_u.c
CXX  <=  App/App.cpp
LINK =>  app
The project has been built in debug hardware mode.
make[1]: Leaving directory '/home/work/Desktop/Project-work/linux-


sgx/linux/installer/bin/sgxsdk/SampleCode/LocalAttestation'
work@work:~/Desktop/Project-work/linux-sgx/linux/installer/bin/sgxsdk/SampleCode/LocalAttestation$ ./app

Load Enclave Failure
Available Enclaves
Enclave1 - EnclaveID 0
Enclave2 - EnclaveID 0
Enclave3 - EnclaveID 0Enclave1_test_create_session Ecall failed: Error code is 2002

Hit a key....


its showing the error EnclaveID 0Enclave1_test_create_session Ecall failed.

**Comment by dimakuv** [comment] 2019-05-14 17:31
Hi @Nidhimidha,

This is not a Graphene-related issue but an SGX SDK issue. Please move this question to the appropriate forum: https://github.com/intel/linux-sgx/issues.

There are several possible reasons you see this error: (1) your computer doesn't have SGX hardware, (2) you incorrectly installed the SGX driver, (3) you run it on an unsupported OS. Maybe something else.

You should try collecting as much info as possible. Check if the SGX driver complains about the LocalAttestation app by looking at `dmesg` log. Build and run LocalAttestation in debug mode and examine the output messages. Check what error code `2002` can meet in the context of SGX SDK.
