### ISSUE TITLE
Fork/ipc bug in shim/test/regression/proc.c

### ISSUE THREAD

**Issue by donporter** [oscarlab/graphene#532] opened 2019-03-18 14:51 UTC
Once PR #497 is landed, this regression test includes some unrelated/commented code that calls fork and tickles some bugs around process creation.  

Just saving this here so we don't lose the issue.

**Comment by mkow** [comment] 2019-07-11 05:25
@donporter #497 was merged. Would you have time to work on this issue?

**Comment by dimakuv** [comment] 2019-07-11 21:38
This would be a good candidate to test my PR on Graphene IPC: https://github.com/oscarlab/graphene/pull/811. I will hopefully look into this regression test.

**Comment by donporter** [comment] 2019-07-19 18:51
Not immediately. I can put it on my to-do list if @dimakuv doesn't do it first.

**Comment by dimakuv** [comment] 2019-07-20 00:11
Added this to my TODO list.

**Comment by dimakuv** [comment] 2019-07-21 00:34
After fixing a bug of "nested C functions" (see https://github.com/oscarlab/graphene/blob/ca64cb4b294c7b9b91c3f0088b054a1e95d5a2b7/LibOS/shim/src/ipc/shim_ipc_pid.c#L197), I see some other issue. But before debugging it, I find the for-loop in `proc.c` very weird:
```c
    for (int i = 0 ; i < 3 ; i++) {
        pid_t pid = fork();
        if (pid) {
            waitpid(pid, NULL, 0);
            exit(0);
        }
    }
```

So imagine we have our first process P1. P1 will create a child P2 and start waiting on it.

P2 inherits `i=1` and goes into the for-loop again. Now P2 creates its child P3 and starts waiting on it. P3 inherits `i=2` and goes into the for-loop... etc etc.

What is the point of this logic? And what does this test show? (Apparently, there are some race conditions / incompatibility of our `proc` implementation with some many children and grandchildren.)

**Comment by mkow** [comment] 2019-07-21 15:05
I think the intention is to create a "path" of `n` processes, i.e.: A -> B -> C -> D. Not sure if we had any bugs which were exposed by this, but sounds like a reasonable test.

**Comment by mkow** [comment] 2020-07-30 23:41
This test was refactored since then and doesn't have this logic commented out. Seems to be stable, so I'm closing this issue as outdated.

**Closed by mkow** 2020-07-30 23:41 UTC
