### ISSUE TITLE
error because of number of threads in the manifest file

### ISSUE THREAD

**Issue by cryptograph** [oscarlab/graphene#65] opened 2017-06-26 20:29 UTC
Hello there, 
I have some issues with multithreaded programms (even with the native helloworld.pthread). There is a variable sgx.thread_num in the manifest file and when I set this variable greater then 32 I receive an error. The problem probably is related to the registration of the enclave structure. The version of SGX-driver is 'cec111a' from March 23rd. 

the error is (from the debug file): of
initializing enclave failed: init_enclave: 1

here is the line with the error from the strace:
ioctl(3, PHN_SET_REGS or RTC_UIE_ON, 0x7ffc378650a0) = 16

Thank you in advance!

**Comment by heartever** [comment] 2017-07-05 13:26
I am not sure, but I guess SGX only support at most 8 simultaneously running threads, which is limited by the number of thread control structure (TCS).

**Comment by donporter** [comment] 2018-06-30 15:28
Hi @cryptograph , I am sorry this issue lingered as long as it did.

FWIW, I am not able to reproduce this issue anymore (i.e., I can start helloworld.pthread with 64 threads on the latest master with the SGX driver v1.9) .  I assume it has been fixed in the last year and am closing the issue.  Please let us know if you are still having issues.

**Closed by donporter** 2018-06-30 15:28 UTC
