### ISSUE TITLE
Remote attestation example with Python

### ISSUE THREAD

**Issue by sbellem** [oscarlab/graphene#2588] opened 2021-07-28 03:34 UTC
Is there documentation and/or examples on how to perform remote attestation when using Python in an enclave?

**Comment by dimakuv** [comment] 2021-07-28 06:32
No, there is no documentation or examples particular to Python + SGX Remote attestation.

But you can apply the Secret Provisioning library to your Python workload: https://github.com/oscarlab/graphene/tree/master/Examples/ra-tls-secret-prov. The variant you will probably be interested in is `secret_prov_pf_client`.

I also recommend to read our docs: https://graphene.readthedocs.io/en/latest/attestation.html#high-level-secret-provisioning-interface.

**Comment by mkow** [comment] 2021-07-28 16:58
This is a question, not a bug, so I'm closing it. @sbellem please use our mailing list (support@graphene-project.io) for usage questions/support.

**Closed by mkow** 2021-07-28 16:58 UTC

**Comment by sbellem** [comment] 2021-07-29 00:06
Thanks. Did not know that you do not use issues for questions. Sorry.

**Comment by mkow** [comment] 2021-07-29 00:25
No problem :)
But FYI, we have "IMPORTANT: please do not post general questions here; if you have questions, please use mailing list: support@graphene-project.io" in the issue template you get when creating a new one ;) Anyways, if you still have some questions then please just continue there, we'll try to help.

**Comment by sbellem** [comment] 2021-07-29 02:29
Oh, I am sorry! I was helping with a hackathon, and it was late, and just skimmed super quickly through the comment, and overlooked the IMPORTANT ... and deleted the whole thing to post my question ... sorry.
